### ISSUE TITLE
File path is not being found

### ISSUE THREAD

**Issue by mgruchala** [cms-gem-daq-project/gem-plotting-tools#181] opened 2019-02-14 17:21 UTC
## Brief summary of issue

Whenever we try to run the command:
`plotSbitThreshComp.py --alphaLabels /home/gemuser/ThreshComp.txt` with the `ThreshComp.txt` of the following content:
```
ChamberName	scandate
GE11-X-S-CERN-0007	2019.02.14.16.45 
GE11-X-S-CERN-0007	2019.02.14.17.25
GE11-X-S-CERN-0007	2019.02.14.16.55 
```
or
```
ChamberName	scandate
GE11-X-S-CERN-0007	2019.02.14.16.45    HV ON
GE11-X-S-CERN-0007	2019.02.14.17.25    HV ON, dV = 0
GE11-X-S-CERN-0007	2019.02.14.16.55    HV OFF
```
we always get the output indicating that there is a problem with correct setting the path:
```
Filepath /data/bigdisk/GEM-Data-Taking/GE11_QC8//GE11-X-S-CERN-0007/sbitRate/channelOR//2019.02.14.16.45  does not exist!
Please cross-check, exiting!
```
### Types of issue

- [ ] Bug report (report an issue with the code)

### Steps to Reproduce (for bugs)

1.Just execute command I have listed above (plotSbitThreshComp.py --alphaLabels /home/gemuser/ThreshComp.txt) with the file of the content that was also listed above.

## Your Environment

* Shell used:/bin/bash

**Comment by mexanick** [comment] 2019-02-14 18:24
the issue is in trailing whitespace at the last line of your input file. Closing as improper usage

**Closed as completed by mexanick** 2019-02-14 18:24 UTC
