### ISSUE TITLE
Detectors cannot be properly configured for sBit Threshold scans

### ISSUE THREAD

**Issue by ElizabethRoseStarling** [cms-gem-daq-project/gem-plotting-tools#281] opened 2020-01-29 15:41 UTC
## Problem summary
The QC8 detectors cannot be properly configured for sBit Threshold scans as a result of the generated chConfig files using strings instead of integers.

### Types of issue

- [X] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Expected Behavior

The chConfig.txt files should use "0" and "1" in place of "False" and "True".

## Current Behavior

Currently, attempting to follow the instructions in [the QC8 shifter instructions](https://twiki.cern.ch/twiki/bin/viewauth/CMS/QC8GuideToTheGalaxy) results in a problem when configuring the chambers for the sBit threshold scan after the daily S-Curves are taken.

> confAllChambers.py --shelf=1 --chConfig --applyMasks --run

results in

> Caught Exception can only convert an array of size 1 to a Python scalar, terminating workers

unless the following commands are issued first:

> sed -i 's/False/0/' /data/bigdisk/GEM-Data-Taking/GE11_QC8/*/scurve/2020.01.29.09.59/SCurveData/chConfig.txt

> sed -i 's/True/1/' /data/bigdisk/GEM-Data-Taking/GE11_QC8/*/scurve/2020.01.29.09.59/SCurveData/chConfig.txt

### Steps to Reproduce (for bugs)

1. From the gem904qc8daq machine, run confAllChambers.py --shelf=1 --chConfig --applyMasks --run

## Possible Solution (for bugs)

Either make the above fixing commands included in the configuring script, or make the chConfig files use ints instead of strings by default.

## Your Environment

* Version used:
* Shell used:

**Comment by lpetre-ulb** [comment] 2020-01-29 15:47
Duplicate of #278 which has been fixed in #279. The bugfix is not yet deployed on the QC8 DAQ machine though.

**Closed as completed by lpetre-ulb** 2020-01-29 15:47 UTC
Labels: Type: Duplicate
